const AFFECTED_LAYERS = Object.freeze([
  'active',
  'baseSnapshot',
  'seed',
  'revisions',
  'backups',
]);

const RETIRED_ROUTE_PATHS = Object.freeze([
  '/services/legacy-giving',
  '/services/retirement/403b-for-groups',
  '/services/planned-giving/generosity-fund',
]);

const BLOCK_ONLY_PATHS = Object.freeze([
  '/services/planned-giving/charitable-gift-annuities',
  '/services/planned-giving/charitable-trusts',
  '/services/planned-giving/endowments',
  '/services/planned-giving/donor-advised-fund',
  '/services/planned-giving/ministry-impact-fund',
]);

export const CONTENT_ADMIN_MIGRATION_AFFECTED_LAYERS = AFFECTED_LAYERS;

export const CONTENT_ADMIN_MIGRATION_ADAPTERS = Object.freeze([
  {
    id: 'managed-path-aliases',
    category: 'compatibility-boundary',
    paths: RETIRED_ROUTE_PATHS,
    helpers: Object.freeze(['DEFAULT_MANAGED_PATH_ALIASES']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'No active, seed, revision, or backup content-bearing route keys or links use retired paths; canonical redirects are confirmed externally.',
  },
  {
    id: 'block-only-page-inventory-reconciliation',
    category: 'snapshot-migration',
    paths: BLOCK_ONLY_PATHS,
    helpers: Object.freeze(['shouldRetireBlockOnlyShellBlock', 'reconcileBlockOnlyManagedBlockInventory']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'No active, seed, revision, or backup block-only route contains a retired shell-owned block shape.',
  },
  {
    id: 'generosity-fund-donor-advised-fund-refresh',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/planned-giving/donor-advised-fund', '/services/planned-giving', '/services']),
    helpers: Object.freeze(['normalizeGenerosityFundPageHierarchyEntry', 'normalizeGenerosityFundRouteLabelsInSettings', 'migrateGenerosityFundSnapshot']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'No active, seed, revision, or backup snapshot contains the retired Generosity Fund route shape, title, or link labels.',
  },
  {
    id: 'retirement-403b-snapshot-repairs',
    category: 'snapshot-migration',
    paths: Object.freeze([
      '/services/retirement/403b',
      '/services/retirement/403b/403b-individual-enrollment',
      '/services/retirement/403b/403b-group-enrollment',
      '/services/retirement/rollovers',
    ]),
    status: 'retired',
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/retirement-403b-snapshot-repairs.json',
    retireWhen: 'Retired after the final zero-finding scan and current-schema restore proof; see the retirement receipt.',
  },
  {
    id: 'planned-giving-retired-static-comparison',
    status: 'retired',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/planned-giving']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/planned-giving-retired-static-comparison.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'qcd-centered-card-grid',
    category: 'content-migration',
    paths: Object.freeze(['/services/planned-giving/qualified-charitable-distribution']),
    helpers: Object.freeze(['migrateQcdCenteredCardGridState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the QCD card grid has the centered presentation and no untouched placeholder cards remain in active, base, revision, or backup snapshots.',
  },
  {
    id: 'online-contributions-step-cards',
    category: 'snapshot-migration',
    paths: Object.freeze(['/online-contributions']),
    helpers: Object.freeze(['migrateOnlineContributionsStepsState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after Online Contributions setup steps use the shared numbered-step preset in active, base, revision, backup, and seed snapshots.',
  },
  {
    id: 'numbered-step-cards-preset-metadata',
    category: 'snapshot-migration',
    paths: Object.freeze([
      '/online-contributions',
      '/services/insurance/ministers-group-life-plan',
      '/services/retirement/403b',
      '/services/retirement/403b/403b-group-enrollment',
      '/services/retirement/403b/403b-individual-enrollment',
    ]),
    helpers: Object.freeze(['migrateNumberedStepCardsState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after all numbered card-grid snapshots carry explicit step-cards preset metadata and the shared renderer contract is proven at every target viewport.',
  },
  {
    id: 'site-feature-repeatable-content-fields',
    category: 'content-migration',
    paths: Object.freeze([
      '/',
      '/about-us',
      '/about-us/impact',
      '/services',
      '/services/investments',
      '/services/planned-giving',
      '/services/retirement',
    ]),
    helpers: Object.freeze(['migrateSiteFeatureCollectionsState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after repeatable collection fields exist in active, base, revision, backup, and seed snapshots, and each feature can add/remove/reorder items without code edits.',
  },
  {
    id: 'services-breakdown-card-grid',
    category: 'content-migration',
    paths: Object.freeze(['/services']),
    helpers: Object.freeze(['migrateServicesDirectoryState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the Services directory uses the editable card-grid preset in active, base, revision, backup, and seed snapshots.',
  },
  {
    id: 'about-strategy-billboard-block',
    category: 'content-migration',
    paths: Object.freeze(['/about-us']),
    helpers: Object.freeze(['migrateAboutStrategyBillboardState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the About strategy section uses the shared Billboard contract in active, base, revision, backup, and seed snapshots.',
  },
  {
    id: 'support-library-block-kind',
    category: 'schema-migration',
    paths: Object.freeze(['/services/insurance/ministers-group-life-plan']),
    helpers: Object.freeze(['migrateSupportLibraryBlock', 'migrateSupportLibraryState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the support block uses the support_library kind in active, base, revision, backup, and seed snapshots while preserving the support block ID and payload.',
  },
  {
    id: 'insurance-coverage-cta-fields',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/insurance']),
    helpers: Object.freeze(['migrateInsuranceCoverageCtaState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after published, revision, backup, and seed snapshots use canonical CTA fieldsJson and no public renderer relies on step1FieldsJson.',
  },
  {
    id: 'insurance-feature-columns',
    category: 'content-migration',
    paths: Object.freeze(['/services/insurance']),
    helpers: Object.freeze(['migrateInsuranceFeaturePanelToColumnsBlock', 'migrateInsuranceFeatureColumnsState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after Risk Management and Mission Assure use shared columns presets in active, base, revision, backup, and seed snapshots with no legacy feature-panel instances remaining.',
  },
  {
    id: 'insurance-pc-resource-card-lists',
    category: 'content-migration',
    paths: Object.freeze(['/services/insurance/property-casualty-insurance']),
    helpers: Object.freeze(['migrateInsurancePcResourceCardsState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the two P&C resource cards use card ListJson in active, base, revision, backup, and seed snapshots, with no arrow-prefixed legacy body lines remaining.',
  },
  {
    id: 'retirement-ira-block-shape',
    status: 'retired',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/retirement/iras']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/retirement-ira-block-shape.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'loans-dynamic-block-upgrade',
    status: 'retired',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/loans']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/loans-dynamic-block-upgrade.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'property-casualty-request-repair',
    status: 'retired',
    category: 'snapshot-migration',
    paths: Object.freeze(['/services/insurance/property-casualty-insurance']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/property-casualty-request-repair.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'target-bridge-snapshot-cleanup',
    category: 'snapshot-migration',
    paths: Object.freeze(['all managed routes']),
    helpers: Object.freeze(['stripRetiredTargetBridgeSettingsFromState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'No active, seed, revision, or backup settings contain retired target bridge fields.',
  },
  {
    id: 'split-link-compatibility',
    category: 'compatibility-boundary',
    paths: Object.freeze(['all managed routes']),
    helpers: Object.freeze(['normalizeSplitLinkFieldSettings', 'coerceLinkValueFromFields']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'No persisted block settings or revision snapshots contain split URL/PageRef/OpenInNewWindow fields.',
  },
  {
    id: 'cta-form-slot-compatibility',
    status: 'retired',
    category: 'compatibility-boundary',
    paths: Object.freeze(['all cta_form blocks']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/cta-form-slot-compatibility.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'cga-secure-act-content-compatibility',
    status: 'retired',
    category: 'content-migration',
    paths: Object.freeze(['/services/planned-giving/charitable-gift-annuities']),
    helpers: Object.freeze([]),
    affectedLayers: AFFECTED_LAYERS,
    retirementReceipt: 'docs/content-admin-adapter-retirements/cga-secure-act-content-compatibility.json',
    retireWhen: 'Retired after the final zero-finding scan; see the retirement receipt.',
  },
  {
    id: 'cga-secure-act-card',
    category: 'content-migration',
    paths: Object.freeze(['/services/planned-giving/charitable-gift-annuities']),
    helpers: Object.freeze(['migrateCgaSecureActCardState']),
    affectedLayers: AFFECTED_LAYERS,
    retireWhen: 'Retired after the SECURE 2.0 content and gift bullets are stored in gift_assets.card1Body, legacy secure_act, duplicate BodyHtml fields, and card ListJson are absent, and active, base, revision, and backup snapshots agree.',
  },
]);

export function getContentAdminMigrationAdapterInventory() {
  return CONTENT_ADMIN_MIGRATION_ADAPTERS;
}
